[2024-05-07T08:33:54.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T08:33:54.326+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_airbyte_job_example.trigger_dbt_cloud_job manual__2024-05-07T08:32:40.098100+00:00 [queued]>
[2024-05-07T08:33:54.338+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_airbyte_job_example.trigger_dbt_cloud_job manual__2024-05-07T08:32:40.098100+00:00 [queued]>
[2024-05-07T08:33:54.339+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-07T08:33:54.356+0000] {taskinstance.py:2327} INFO - Executing <Task(DbtCloudRunJobOperator): trigger_dbt_cloud_job> on 2024-05-07 08:32:40.098100+00:00
[2024-05-07T08:33:54.366+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-07T08:33:54.367+0000] {standard_task_runner.py:63} INFO - Started process 121 to run task
[2024-05-07T08:33:54.368+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_airbyte_job_example', 'trigger_dbt_cloud_job', 'manual__2024-05-07T08:32:40.098100+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/dag_aribyte_ex.py', '--cfg-path', '/tmp/tmpdok1kgng']
[2024-05-07T08:33:54.371+0000] {standard_task_runner.py:91} INFO - Job 168: Subtask trigger_dbt_cloud_job
[2024-05-07T08:33:54.422+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_airbyte_job_example.trigger_dbt_cloud_job manual__2024-05-07T08:32:40.098100+00:00 [running]> on host c811ecd915dc
[2024-05-07T08:33:54.523+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_airbyte_job_example' AIRFLOW_CTX_TASK_ID='trigger_dbt_cloud_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T08:32:40.098100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-07T08:32:40.098100+00:00'
[2024-05-07T08:33:54.525+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T08:33:54.535+0000] {connection.py:274} WARNING - Connection schemes (type: dbt_cloud) shall not contain '_' according to RFC3986.
[2024-05-07T08:33:54.536+0000] {base.py:84} INFO - Using connection ID 'dbtconn' for task execution.
[2024-05-07T08:33:56.346+0000] {dbt.py:164} INFO - Waiting for job run 70403108816374 to terminate.
[2024-05-07T08:33:56.347+0000] {dbt.py:504} INFO - Getting the status of job run 70403108816374.
[2024-05-07T08:33:56.832+0000] {dbt.py:509} INFO - Current status of job run 70403108816374: STARTING
[2024-05-07T08:43:56.809+0000] {dbt.py:504} INFO - Getting the status of job run 70403108816374.
[2024-05-07T08:43:57.342+0000] {dbt.py:509} INFO - Current status of job run 70403108816374: ERROR
[2024-05-07T08:43:57.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T08:43:57.361+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/operators/dbt.py", line 175, in execute
    raise DbtCloudJobRunException(f"Job run {self.run_id} has failed or has been cancelled.")
airflow.providers.dbt.cloud.hooks.dbt.DbtCloudJobRunException: Job run 70403108816374 has failed or has been cancelled.
[2024-05-07T08:43:57.367+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=trigger_airbyte_job_example, task_id=trigger_dbt_cloud_job, execution_date=20240507T083240, start_date=20240507T083354, end_date=20240507T084357
[2024-05-07T08:43:57.389+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 168 for task trigger_dbt_cloud_job (Job run 70403108816374 has failed or has been cancelled.; 121)
[2024-05-07T08:43:57.430+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T08:43:57.455+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T08:43:57.460+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
