[2024-04-16T07:05:04.278+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T07:05:04.344+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_airbyte_job_example.airbyte_check_sync scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T07:05:04.381+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_airbyte_job_example.airbyte_check_sync scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T07:05:04.382+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T07:05:04.441+0000] {taskinstance.py:2327} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-04-15 00:00:00+00:00
[2024-04-16T07:05:04.455+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T07:05:04.459+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-04-16T07:05:04.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_airbyte_job_example', 'airbyte_check_sync', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag_aribyte_ex.py', '--cfg-path', '/tmp/tmparmcammx']
[2024-04-16T07:05:04.481+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask airbyte_check_sync
[2024-04-16T07:05:04.634+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_airbyte_job_example.airbyte_check_sync scheduled__2024-04-15T00:00:00+00:00 [running]> on host ff62e46d2b31
[2024-04-16T07:05:05.010+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_airbyte_job_example' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-16T07:05:05.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T07:05:05.015+0000] {baseoperator.py:399} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-04-16T07:05:05.063+0000] {base.py:84} INFO - Using connection ID '***_call_airbyte' for task execution.
[2024-04-16T07:05:05.177+0000] {airbyte.py:104} INFO - Waiting for job 162 to complete.
[2024-04-16T07:06:06.893+0000] {base.py:84} INFO - Using connection ID '***_call_airbyte' for task execution.
[2024-04-16T07:06:06.919+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T07:06:06.931+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 91, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2024-04-16T07:06:06.939+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=trigger_airbyte_job_example, task_id=airbyte_check_sync, execution_date=20240415T000000, start_date=20240416T070504, end_date=20240416T070606
[2024-04-16T07:06:06.957+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task airbyte_check_sync (Job failed: 
<Response [200]>; 65)
[2024-04-16T07:06:07.004+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T07:06:07.020+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T07:06:07.023+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
